version: '3.1'

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - .:/code
    networks:
      - store

  mongo:
    image: mongo
    container_name: mongo
    ports:
       - '27017:27017'
    environment:
      MONGO_DATABASE: 'store_db'
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: super_password
      MONGODB_DATABASE_URL: mongosh mongodb://root:super_password@mongo:27017
    volumes:
      - store_db:/var/lib/mongo
    networks:
      - store

networks:
  store:
    name: store
    driver: bridge

volumes:
  store_db:
